/*
 * 
 * 		SAP UI development toolkit for HTML5 (SAPUI5)
 * 		(c) Copyright 2009-2015 SAP SE. All rights reserved
 * 	
 */
jQuery.sap.declare("sap.suite.ui.commons.ProcessFlowRenderer");jQuery.sap.require("sap.suite.ui.commons.ProcessFlowLaneHeader");sap.suite.ui.commons.ProcessFlowRenderer={};
sap.suite.ui.commons.ProcessFlowRenderer.render=function(r,c){var s=this._getZoomStyleClass(c),C,l,L,p=sap.suite.ui.commons.ProcessFlowRenderer,a,o;o=p._renderBasicStructure(r,c);if(o){return;}try{C=c._getOrCreateProcessFlow();l=c._getOrCreateLaneMap();a=c._getConnectionsMap();}catch(e){c._handleException(e);return;}r.write("<table");r.writeAttribute("id",c.getId()+"-table");r.writeAttribute("aria-label",c._getAriaText());r.addClass("sapSuiteUiCommonsPF");r.addClass(s);r.writeClasses();r.write(">");L=Object.keys(l).length;p._renderTableHeader(r,c,l,L);p._renderTableBody(r,c,L,C,a);r.write("</table>");r.write("</div>");r.write("</div>");this._writeCounter(r,c,"Right");r.renderControl(c._getScrollingArrow("right"));r.write("</div>");};
sap.suite.ui.commons.ProcessFlowRenderer._renderNormalNodeHeader=function(r,c,n,a,l){r.write("<th colspan=\"3\">");r.renderControl(n);r.write("</th>");if(a<l-1){r.write("<th colspan=\"2\">");var L=sap.suite.ui.commons.ProcessFlowLaneHeader.createNewProcessSymbol(c._isHeaderMode());L.attachPress(jQuery.proxy(c.ontouchend,c));r.renderControl(L);r.write("</th>");}};
sap.suite.ui.commons.ProcessFlowRenderer._renderMergedNodeHeader=function(r,c,n,a,l,b){var N=c._mergeLaneIdNodeStates(l);n.setState(N);a++;var d=a*3+(a-1)*2;r.write("<th colspan=\""+d+"\">");r.renderControl(n);r.write("</th>");if(b){r.write("<th colspan=\"2\">");var L=sap.suite.ui.commons.ProcessFlowLaneHeader.createNewProcessSymbol(c._isHeaderMode());L.attachPress(jQuery.proxy(c.ontouchend,c));r.renderControl(L);r.write("</th>");}};
sap.suite.ui.commons.ProcessFlowRenderer._renderNode=function(r,c,n,i){if(i){r.writeAttribute("tabindex",0);r.writeAttributeEscaped("aria-label",n._getAriaText());r.write(">");i=false;}n._setParentFlow(c);n._setZoomLevel(c.getZoomLevel());n._setFoldedCorner(c.getFoldedCorners());r.renderControl(n);return i;};
sap.suite.ui.commons.ProcessFlowRenderer._renderConnection=function(r,c,a,i){if(i){if(a.getAggregation("_labels")&&a.getAggregation("_labels").length>0){r.writeAttribute("tabindex",0);}r.write(">");i=false;}a.setZoomLevel(c.getZoomLevel());c.addAggregation("_connections",a);r.renderControl(a);return i;};
sap.suite.ui.commons.ProcessFlowRenderer._renderTableHeader=function(r,c,l,a){var L,n=null,N=null,o,d;r.write("<thead");r.writeAttribute("id",c.getId()+"-thead");r.write(">");r.write("<tr");r.addClass("sapSuiteUiCommonsPFHeader");r.addClass("sapSuiteUiCommonsPFHeaderHidden");if(c.getShowLabels()){r.addClass("sapSuiteUiPFWithLabel");}r.writeClasses();r.write(">");r.write("<th></th>");L=0;while(L<a-1){r.write("<th></th><th></th><th></th><th></th><th></th>");L++;}r.write("<th></th><th></th><th></th>");r.write("<th></th>");r.write("</tr>");r.write("<tr");r.addClass("sapSuiteUiCommonsPFHeaderRow");r.writeClasses();r.write(">");r.write("<th>");o=sap.suite.ui.commons.ProcessFlowLaneHeader.createNewStartSymbol(c._isHeaderMode());r.renderControl(o);r.write("</th>");L=0;var A=0;var b=[];var s="1";d=false;while(L<(a-1)){n=l[L];N=l[L+1];if(n.getLaneId()+s===N.getLaneId()){A=A+1;b.push(n.getState());}else{if(A===0){this._renderNormalNodeHeader(r,c,n,L,a);}else{b.push(n.getState());d=true;this._renderMergedNodeHeader(r,c,n,A,b,d);b=[];A=0;}}L++;}if(A===0){if(!N){N=l[0];}this._renderNormalNodeHeader(r,c,N,L,a);}else{b.push(N.getState());d=false;this._renderMergedNodeHeader(r,c,n,A,b,d);A=0;}r.write("<th>");o=sap.suite.ui.commons.ProcessFlowLaneHeader.createNewEndSymbol(c._isHeaderMode());r.renderControl(o);r.write("</th>");r.write("</tr>");r.write("</thead>");};
sap.suite.ui.commons.ProcessFlowRenderer._renderTableBody=function(r,c,l,a,b){var i,j,m,M,n;var s=sap.suite.ui.commons.ProcessFlowRenderer._checkIfHighlightedOrSelectedNodesExists(b);r.write("<tbody>");m=a.length;if(m>0){r.write("<tr>");r.write("<td");r.writeAttribute("colspan",(l*5).toString());r.write(">");r.write("</tr>");}i=0;while(i<m){r.write("<tr>");r.write("<td></td>");M=a[i].length;j=0;while(j<M-1){n=a[i][j];var d=true;if((j==0)||(j%2)){r.write("<td");}else{r.write("<td colspan=\"4\"");if(sap.ui.Device.browser.name==="cr"){r.addClass("sapSuiteUiCommonsProcessFlowZIndexForConnectors");r.writeClasses();}}if(n){if(n instanceof sap.suite.ui.commons.ProcessFlowNode){d=sap.suite.ui.commons.ProcessFlowRenderer._renderNode(r,c,n,d);}else{n._setShowLabels(c.getShowLabels());sap.suite.ui.commons.ProcessFlowRenderer._setLabelsInConnection(a,b,n,{row:i,column:j},c,s);d=sap.suite.ui.commons.ProcessFlowRenderer._renderConnection(r,c,n,d);}}if(d){r.write(">");}r.write("</td>");j++;}r.write("<td></td>");r.write("<td></td>");r.write("</tr>");i++;}r.write("</tbody>");};
sap.suite.ui.commons.ProcessFlowRenderer._renderBasicStructure=function(r,c){r.write("<div");r.writeAttribute("aria-label","process flow");r.writeControlData(c);r.addClass("sapSuiteUiPFContainer");if(c._arrowScrollable){r.addClass("sapPFHScrollable");if(c._bPreviousScrollForward){r.addClass("sapPFHScrollForward");}else{r.addClass("sapPFHNoScrollForward");}if(c._bPreviousScrollBack){r.addClass("sapPFHScrollBack");}else{r.addClass("sapPFHNoScrollBack");}}else{r.addClass("sapPFHNotScrollable");}r.writeClasses();r.write(">");this._writeCounter(r,c,"Left");r.renderControl(c._getScrollingArrow("left"));r.write("<div");r.writeAttribute("id",c.getId()+"-scrollContainer");r.addClass("sapSuiteUiScrollContainerPF");r.addClass("sapSuiteUiDefaultCursorPF");r.writeClasses();r.write(">");r.write("<div");r.writeAttribute("id",c.getId()+"-scroll-content");r.writeAttribute("tabindex",0);r.write(">");if(!c.getLanes()||c.getLanes().length==0){r.write("</div>");r.write("</div>");r.write("</div>");return true;}return false;};
sap.suite.ui.commons.ProcessFlowRenderer._getZoomStyleClass=function(c){switch(c.getZoomLevel()){case sap.suite.ui.commons.ProcessFlowZoomLevel.One:return"sapSuiteUiCommonsPFZoomLevel1";case sap.suite.ui.commons.ProcessFlowZoomLevel.Two:return"sapSuiteUiCommonsPFZoomLevel2";case sap.suite.ui.commons.ProcessFlowZoomLevel.Three:return"sapSuiteUiCommonsPFZoomLevel3";case sap.suite.ui.commons.ProcessFlowZoomLevel.Four:return"sapSuiteUiCommonsPFZoomLevel4";}};
sap.suite.ui.commons.ProcessFlowRenderer._setLabelsInConnection=function(c,a,b,p,C,s){for(var i=0;i<a.length;i++){var o=a[i];if(o&&o.label){for(var j=0;j<o.connectionParts.length;j++){var d=o.connectionParts[j];if(d.x===p.column&&d.y===p.row){if(c[p.row][p.column+1]instanceof sap.suite.ui.commons.ProcessFlowNode&&c[p.row][p.column+1].getNodeId()===o.targetNode.getNodeId()){sap.suite.ui.commons.ProcessFlowRenderer._setLineTypeInLabel(o,s);if(o.label.getEnabled()){if(o.label.hasListeners("press")){o.label.detachEvent("press",C._handleLabelClick,C);}o.label.attachPress(C._handleLabelClick,C);}b.addAggregation("_labels",o.label,true);}}}}}};
sap.suite.ui.commons.ProcessFlowRenderer._setLineTypeInLabel=function(c,s){var C=false;var b=false;if(c.sourceNode.getSelected()&&c.targetNode.getSelected()){C=true;c.label._setSelected(true);}else{c.label._setSelected(false);}if(c.sourceNode.getHighlighted()&&c.targetNode.getHighlighted()){b=true;c.label._setHighlighted(true);}else{c.label._setHighlighted(false);}if(s&&!C&&!b){c.label._setDimmed(true);}else{c.label._setDimmed(false);}};
sap.suite.ui.commons.ProcessFlowRenderer._checkIfHighlightedOrSelectedNodesExists=function(c){var s=false;for(var i=0;i<c.length;i++){var C=c[i];if(C.label){if(C.sourceNode.getSelected()&&C.targetNode.getSelected()||C.sourceNode.getHighlighted()&&C.targetNode.getHighlighted()){s=true;}}}return s;};
sap.suite.ui.commons.ProcessFlowRenderer._writeCounter=function(r,c,d){r.write("<span");r.writeAttribute("id",c.getId()+"-counter"+d);r.addClass("suiteUiPFHCounter");r.addClass("suiteUiPFHCounter"+d);r.writeClasses();r.write(">");r.writeEscaped("0");r.write("</span>");};
