/*!
 * 
 * 		SAP UI development toolkit for HTML5 (SAPUI5)
 * 		(c) Copyright 2009-2015 SAP SE. All rights reserved
 * 	
 */
jQuery.sap.declare("sap.suite.ui.commons.ProcessFlowLaneHeader");jQuery.sap.require("sap.suite.ui.commons.library");jQuery.sap.require("sap.ui.core.Control");sap.ui.core.Control.extend("sap.suite.ui.commons.ProcessFlowLaneHeader",{metadata:{library:"sap.suite.ui.commons",properties:{"text":{type:"string",group:"Misc",defaultValue:null},"iconSrc":{type:"sap.ui.core.URI",group:"Misc",defaultValue:null},"position":{type:"int",group:"Misc",defaultValue:null},"laneId":{type:"string",group:"Misc",defaultValue:null},"state":{type:"object",group:"Misc",defaultValue:null},"zoomLevel":{type:"sap.suite.ui.commons.ProcessFlowZoomLevel",group:"Misc",defaultValue:null}},events:{"press":{parameters:{"oEvent":{type:"object"}}}}}});sap.suite.ui.commons.ProcessFlowLaneHeader.M_EVENTS={'press':'press'};jQuery.sap.require("sap.ui.core.IconPool");jQuery.sap.require("sap.m.Image");sap.suite.ui.commons.ProcessFlowLaneHeader.prototype._oResBundle=null;sap.suite.ui.commons.ProcessFlowLaneHeader.prototype._mergedLanePosition=null;sap.suite.ui.commons.ProcessFlowLaneHeader.symbolType={startSymbol:"startSymbol",endSymbol:"endSymbol",processSymbol:"processSymbol",standardType:"standardType"};sap.suite.ui.commons.ProcessFlowLaneHeader._constants={halfGapSize:0.0241,minPercentage:0.025,ringThickness:5,ringInnerRadius:24,positionX:32,positionY:32,outerCircleRadius:32,outerCircleStrokeColor:"OuterCircleStrikeColor",outerCircleStrokeWidth:1,sectorPositiveColor:"suiteUiCommonsProcessFlowHeaderPositiveColor",sectorNegativeColor:"suiteUiCommonsProcessFlowHeaderNegativeColor",sectorNeutralColor:"suiteUiCommonsProcessFlowHeaderNeutralColor",sectorCriticalColor:"suiteUiCommonsProcessFlowHeaderCriticalColor",sectorPlannedColor:"suiteUiCommonsProcessFlowHeaderPlannedColor",ellipsis:'...',ellipsisLength:3};
sap.suite.ui.commons.ProcessFlowLaneHeader.prototype.init=function(){this._virtualTableSpan=1;if(!this._oResBundle){this._oResBundle=sap.ui.getCore().getLibraryResourceBundle("sap.suite.ui.commons");}};
sap.suite.ui.commons.ProcessFlowLaneHeader.prototype.exit=function(){this._destroyImage();this.$().unbind("click",this.ontouchend);};
sap.suite.ui.commons.ProcessFlowLaneHeader.prototype.onBeforeRendering=function(){this.$("lh-icon").off('click',jQuery.proxy(this.ontouchend,this));this.$().unbind("click",this.ontouchend);};
sap.suite.ui.commons.ProcessFlowLaneHeader.prototype.onAfterRendering=function(){var t=this.$();var $=this.$("lh-icon");var c='click';if(sap.ui.Device.support.touch){c='touchend';}if($.length>0){$.on(c,jQuery.proxy(this.ontouchend,this));$.css("cursor","inherit");}this.$().bind("click",jQuery.proxy(this.ontouchend,this));if(this._isHeaderMode()){t.addClass("suiteUiProcessFlowLaneHeaderPointer");}else{t.removeClass("suiteUiProcessFlowLaneHeaderPointer");}if(sap.ui.Device.browser.msie||sap.ui.Device.browser.mozilla){this.$("lh-text").css("word-break","break-all");}if(!this._ellipsisDisabled&&!sap.suite.ui.commons.ProcessFlowLaneHeader._hasNativeLineClamp){this._clampText();}};
sap.suite.ui.commons.ProcessFlowLaneHeader.prototype.ontouchend=function(e){if(e&&!e.isDefaultPrevented()){e.preventDefault();}if(this){this.firePress(this);}if(e&&!e.isPropagationStopped()){e.stopPropagation();}if(e&&!e.isImmediatePropagationStopped()){e.stopImmediatePropagation();}};
sap.suite.ui.commons.ProcessFlowLaneHeader.prototype._setMergedPosition=function(p){this._mergedLanePosition=p;};
sap.suite.ui.commons.ProcessFlowLaneHeader.prototype._getSymbolType=function(){return this._oSymbolType?this._oSymbolType:sap.suite.ui.commons.ProcessFlowLaneHeader.symbolType.standardType;};
sap.suite.ui.commons.ProcessFlowLaneHeader.prototype._setSymbolType=function(s,c){c._oSymbolType=s;};
sap.suite.ui.commons.ProcessFlowLaneHeader.prototype._getImage=function(i,s){this._destroyImage();if(this._oImageControl){this._oImageControl.setSrc(s);}else{this._oImageControl=sap.ui.core.IconPool.createControlByURI(s,sap.m.Image);this._oImageControl.sId=i;this._oImageControl.setParent(this,null,true);}if(this._oImageControl instanceof sap.ui.core.Icon){this._oImageControl.setUseIconTooltip(false);}return this._oImageControl;};
sap.suite.ui.commons.ProcessFlowLaneHeader.prototype._setHeaderMode=function(i){this._bHeaderMode=i;};
sap.suite.ui.commons.ProcessFlowLaneHeader._setVirtualTableSpan=function(e){this._virtualTableSpan=e;};
sap.suite.ui.commons.ProcessFlowLaneHeader._getVirtualTableSpan=function(){return this._virtualTableSpan;};
sap.suite.ui.commons.ProcessFlowLaneHeader.prototype._isHeaderMode=function(){return this._bHeaderMode;};
sap.suite.ui.commons.ProcessFlowLaneHeader.prototype._clampValues=function(c,m,a){var i=c.length-1,C=false,v;while(i>=0){v=c[i];if(v<m){c[i]=a;C=true;}i--;}return C;};
sap.suite.ui.commons.ProcessFlowLaneHeader.prototype._rescaleToUnit=function(r,m){var R,i,v,V,a,b;if(!m){m=0;}i=r.length-1;R=0;v=V=0;while(i>=0){a=r[i];if(a>0){if(a<=m){V++;}else{R+=r[i];}v++;}i--;}R-=(v-V)*m;b=(1-v*m)/R;i=r.length-1;while(i>=0){a=r[i];if(a>0){if(a<=m){r[i]=m;}else{r[i]=(a-m)*b+m;}}i--;}};
sap.suite.ui.commons.ProcessFlowLaneHeader.prototype._countGaps=function(a){var i=a.length-1,g=0;while(i>=0){if(a[i]>0){g++;}i--;}if(g===1){g=0;}return g;};
sap.suite.ui.commons.ProcessFlowLaneHeader.prototype._rescaleByFactor=function(r,f){var i=r.length-1;while(i>=0){r[i]*=f;i--;}};
sap.suite.ui.commons.ProcessFlowLaneHeader.prototype._colorMap=[sap.suite.ui.commons.ProcessFlowLaneHeader._constants.sectorPositiveColor,sap.suite.ui.commons.ProcessFlowLaneHeader._constants.sectorNegativeColor,sap.suite.ui.commons.ProcessFlowLaneHeader._constants.sectorNeutralColor,sap.suite.ui.commons.ProcessFlowLaneHeader._constants.sectorPlannedColor,sap.suite.ui.commons.ProcessFlowLaneHeader._constants.sectorCriticalColor];
sap.suite.ui.commons.ProcessFlowLaneHeader.prototype._calculateSectorRangeDefinitions=function(a,f){var d=[],c=-Math.PI/2,C,I=a.length,i=0;while(i<I){if(a[i]>0){C=c+2*Math.PI*a[i];d.push({start:c,end:C,color:this._colorMap[i]});c=C+f;}i++;}return d;};
sap.suite.ui.commons.ProcessFlowLaneHeader.prototype._renderDonutPercentages=function(r){var s=this.getState(),g=0,S,p=[0,0,0,0],f,c,h=sap.suite.ui.commons.ProcessFlowLaneHeader._constants.halfGapSize,R=sap.suite.ui.commons.ProcessFlowLaneHeader._constants.ringInnerRadius,i=sap.suite.ui.commons.ProcessFlowLaneHeader._constants.ringThickness,a=sap.suite.ui.commons.ProcessFlowLaneHeader._constants.ringInnerRadius+i,o=sap.suite.ui.commons.ProcessFlowLaneHeader._constants.outerCircleStrokeColor,O=sap.suite.ui.commons.ProcessFlowLaneHeader._constants.outerCircleStrokeWidth,b=sap.suite.ui.commons.ProcessFlowLaneHeader._constants.outerCircleRadius,P=sap.suite.ui.commons.ProcessFlowLaneHeader._constants.positionX,d=sap.suite.ui.commons.ProcessFlowLaneHeader._constants.positionY,m=sap.suite.ui.commons.ProcessFlowLaneHeader._constants.minPercentage;if(s&&Object.prototype.toString.call(s)==='[object Array]'&&(s.length>0)){s.forEach(function(e){switch(e.state){case sap.suite.ui.commons.ProcessFlowNodeState.Positive:p[0]=e.value;break;case sap.suite.ui.commons.ProcessFlowNodeState.Negative:p[1]=e.value;break;case sap.suite.ui.commons.ProcessFlowNodeState.Neutral:p[2]=e.value;break;case sap.suite.ui.commons.ProcessFlowNodeState.Planned:p[3]=e.value;break;case sap.suite.ui.commons.ProcessFlowNodeState.Critical:p[4]=e.value;break;default:p[3]=e.value;}});this._clampValues(p,0,0);this._rescaleToUnit(p);this._rescaleToUnit(p,m);g=this._countGaps(p);f=(1-g*h/Math.PI);this._rescaleByFactor(p,f);this._renderCircle(r,o,O,P,d,b);if(g>0){S=this._calculateSectorRangeDefinitions(p,2*h);this._renderDonutSectors(r,S,P,d,R,a);}else{c=this._selectColor(p);this._renderCircle(r,c,i,P,d,R+i/2);}}else{this._renderCircle(r,o,O,P,d,b);}};
sap.suite.ui.commons.ProcessFlowLaneHeader.prototype._renderCircle=function(r,s,a,p,b,c){r.write("<circle");r.writeAttribute("id",this.getId()+"-donut-circle");if(s!=sap.suite.ui.commons.ProcessFlowLaneHeader._constants.outerCircleStrokeColor){r.writeAttribute("class","suiteUiCommonsProcessFlowHeaderIconFill "+s);}else{r.writeAttribute("class","suiteUiCommonsProcessFlowHeaderIconFill");}r.writeAttribute("stroke-width",a);r.writeAttribute("cx",p);r.writeAttribute("cy",b);r.writeAttribute("r",c);r.write("></circle>");};
sap.suite.ui.commons.ProcessFlowLaneHeader.prototype._renderDonutSectors=function(r,s,p,a,b,c){var i=0,d=s.length,S,P;while(i<d){S=s[i];P=this._getDonutSectorPath(p,a,S.start,S.end,b,c);r.write("<path");r.writeAttribute("id",this.getId()+"-donut-segment-"+i);r.writeAttribute("d",P);r.writeAttribute("class",S.color);r.writeAttribute("opacity","1");r.write("></path>");i++;}};
sap.suite.ui.commons.ProcessFlowLaneHeader.prototype._selectColor=function(p){var c;if(p[0]){c=sap.suite.ui.commons.ProcessFlowLaneHeader._constants.sectorPositiveColor;}else if(p[1]){c=sap.suite.ui.commons.ProcessFlowLaneHeader._constants.sectorNegativeColor;}else if(p[2]){c=sap.suite.ui.commons.ProcessFlowLaneHeader._constants.sectorNeutralColor;}else if(p[3]){c=sap.suite.ui.commons.ProcessFlowLaneHeader._constants.sectorPlannedColor;}else if(p[4]){c=sap.suite.ui.commons.ProcessFlowLaneHeader._constants.sectorCriticalColor;}else{c=sap.suite.ui.commons.ProcessFlowLaneHeader._constants.sectorNeutralColor;}return c;};
sap.suite.ui.commons.ProcessFlowLaneHeader.prototype._getDonutSectorPath=function(p,a,s,e,r,b){var o=0,P,c,d,f,S,g,E,h,i;if((e-s)%(Math.PI*2)>Math.PI){o=1;}g=Math.cos(s);E=Math.cos(e);h=Math.sin(s);i=Math.sin(e);P=(p+r*g).toFixed(3)+','+(a+r*h).toFixed(3);c=(p+b*g).toFixed(3)+','+(a+b*h).toFixed(3);d=(p+b*E).toFixed(3)+','+(a+b*i).toFixed(3);f=(p+r*E).toFixed(3)+','+(a+r*i).toFixed(3);S="M"+P+"L"+c+"A"+b+','+b+" 0 "+o+" 1 "+d+"L"+f+"A"+r+','+r+" 0 "+o+" 0 "+P+"z";return S;};
sap.suite.ui.commons.ProcessFlowLaneHeader.prototype._destroyImage=function(){if(this._oImageControl){this._oImageControl.destroy();}this._oImageControl=null;};
sap.suite.ui.commons.ProcessFlowLaneHeader.prototype._clampText=function(){var $=this.$("lh-text").length?this.$("lh-text"):null,t=this.getText(),l="",e=sap.suite.ui.commons.ProcessFlowLaneHeader._constants.ellipsis,E=sap.suite.ui.commons.ProcessFlowLaneHeader._constants.ellipsisLength,s=E+1,m,i=t.length,M,v;if($){M=parseInt($.css("height").slice(0,-2),10);if($[0].scrollHeight>M){v=$.css("visibility");$.css("visibility","hidden");l=t;do{m=(s+i)>>1;$.textContent=t.slice(0,m-E)+e;if($.scrollHeight>M){i=m;}else{s=m;l=$.textContent;}}while(i-s>1);$.css("visibility",v);}if($.scrollHeight>M){$.textContent=l;}}};
sap.suite.ui.commons.ProcessFlowLaneHeader._hasNativeLineClamp=(function(){return document.documentElement.style.webkitLineClamp!==undefined;}());
sap.suite.ui.commons.ProcessFlowLaneHeader.prototype._getAriaText=function(){var a="";var s=this.getState();if(s){var b=[];for(var i in s){b.push(s[i].value);}this._clampValues(b,0,0);this._rescaleToUnit(b);a=this._oResBundle.getText('PF_ARIA_STATUS');for(var j in s){if(s[j].value!=0){var v=" "+Math.round(b[j]*100)+"% "+s[j].state+",";a=a.concat(v);}}a=a.slice(0,-1);}return a;};
sap.suite.ui.commons.ProcessFlowLaneHeader.prototype._getSymbolAriaText=function(){var a="";switch(this._getSymbolType()){case sap.suite.ui.commons.ProcessFlowLaneHeader.symbolType.startSymbol:a=this._oResBundle.getText('PF_ARIA_SYMBOL_LANE_START');break;case sap.suite.ui.commons.ProcessFlowLaneHeader.symbolType.endSymbol:a=this._oResBundle.getText('PF_ARIA_SYMBOL_LANE_END');break;case sap.suite.ui.commons.ProcessFlowLaneHeader.symbolType.processSymbol:a=this._oResBundle.getText('PF_ARIA_SYMBOL_LANE_PROCESS');break;}return a;};
sap.suite.ui.commons.ProcessFlowLaneHeader.createNewStartSymbol=function(i){var s=sap.suite.ui.commons.ProcessFlowLaneHeader,S=new sap.suite.ui.commons.ProcessFlowLaneHeader({laneId:"processFlowLaneStart"});S._setSymbolType(s.symbolType.startSymbol,S);S._setHeaderMode(i);return S;};
sap.suite.ui.commons.ProcessFlowLaneHeader.createNewEndSymbol=function(i){var s=sap.suite.ui.commons.ProcessFlowLaneHeader,e=new sap.suite.ui.commons.ProcessFlowLaneHeader({laneId:"processFlowLaneEnd"});e._setSymbolType(s.symbolType.endSymbol,e);e._setHeaderMode(i);return e;};
sap.suite.ui.commons.ProcessFlowLaneHeader.createNewProcessSymbol=function(i){var s=sap.suite.ui.commons.ProcessFlowLaneHeader,p=new sap.suite.ui.commons.ProcessFlowLaneHeader({laneId:"processFlowLaneProcess",iconSrc:"sap-icon://process"});p._setSymbolType(s.symbolType.processSymbol,p);p._setHeaderMode(i);return p;};
sap.suite.ui.commons.ProcessFlowLaneHeader.enableEllipsisSupportForText=function(i){this._ellipsisDisabled=!i;};
sap.suite.ui.commons.ProcessFlowLaneHeader.prototype.getPosition=function(){if(this._mergedLanePosition){return this._mergedLanePosition;}else{return this.getProperty("position");}};
