/*!
 * (c) Copyright 2010-2017 SAP SE or an SAP affiliate company.
 */
jQuery.sap.declare("sap.zen.dsh.AnalyticGrid");jQuery.sap.require("sap.zen.dsh.library");jQuery.sap.require("sap.ui.core.Control");sap.ui.core.Control.extend("sap.zen.dsh.AnalyticGrid",{metadata:{library:"sap.zen.dsh",properties:{"width":{type:"sap.ui.core.CSSSize",group:"Appearance",defaultValue:null},"height":{type:"sap.ui.core.CSSSize",group:"Appearance",defaultValue:null},"selectionVariant":{type:"object",group:"Data",defaultValue:null},"queryName":{type:"string",group:"Data",defaultValue:null},"systemAlias":{type:"string",group:"Data",defaultValue:null}}}});var DSH_deployment=true;var sapbi_dshControl;var sapbi_ajaxHandler=sapbi_ajaxHandler||{};window.sapbi_page=window.sapbi_page||{};sapbi_page.getParameter=sapbi_page.getParameter||function(){return"";};var sapbi_MIMES_PIXEL=sapbi_MIMES_PIXEL||"";sapbi_page.staticMimeUrlPrefix=sap.ui.resource("sap.zen.dsh","rt/");if(!window.sap){window.sap={};}if(!sap.zen){sap.zen={};}sap.zen.doReplaceDots=true;
sap.zen.dsh.AnalyticGrid.prototype.init=function(){this.initial=true;this.parameters={};this.dshBaseUrl=sap.ui.resource("sap.zen.dsh","rt/");if(sapbi_dshControl){sapbi_dshControl.logoff();}sapbi_dshControl=this;};
sap.zen.dsh.AnalyticGrid.prototype.doInit=function(){this.repositoryUrl=sap.ui.resource("sap.zen.dsh","applications/");this.addParameter("XQUERY",this.getQueryName());if(this.initial==false){return;}this.initial=false;jQuery.sap.require("sap.zen.dsh.rt.all");if(jQuery.sap.debug()=="true"){jQuery.sap.require("sap.zen.dsh.rt.zen_rt_firefly.js.jszip");jQuery.sap.require("sap.zen.dsh.rt.zen_rt_firefly.js.xlsx");}this.initializeSelectionVariant(this.getSelectionVariant());var t=this;setTimeout(function(){t.doIt();},0);};
sap.zen.dsh.AnalyticGrid.prototype.doIt=function(){this.doInit();sap.zen.dsh.scriptLoaded=true;var t=this;var c=sap.ui.getCore().getConfiguration();language=c.getLocale().getSAPLogonLanguage();if(!language||language==""){language=window.navigator.userLanguage||window.navigator.language;}var a="";if(document.cookie){var m=/(?:sap-usercontext=)*sap-client=(\d{3})/.exec(document.cookie);if(m&&m[1]){a=m[1];}}var u=sap.firefly.XHashMapOfStringByString.create();for(var k in this.parameters){u.put(k,this.parameters[k]);}var d=new sap.zen.DesignStudio();d.setHost(document.location.hostname);d.setPort(document.location.port);d.setProtocol(document.location.protocol.split(":")[0]);d.setClient(a);d.setLanguage(language);if(this.repositoryUrl){d.setRepositoryUrl(this.repositoryUrl);}d.setApplicationPath(this.repositoryUrl+"0ANALYTIC_GRID");d.setApplicationName("0ANALYTIC_GRID");d.setUrlParameter(u);d.setSdkLoaderPath("");d.setHanaMode(true);d.setDshControlId(t.getId());d.setStaticMimesRootPath(this.dshBaseUrl);d.setSystemAlias(this.getSystemAlias());d.setNewBW(true);var p=d.createPage();window[t.getId()+"Buddha"]=p;var s=s||{};s.staticMimeUrlPrefix=this.dshBaseUrl;s.getParameter=function(){return"";};sapbi_MIMES_PIXEL="";window.sapbi_page=s;var z=document.createElement('link');z.setAttribute("type","text/css");z.setAttribute("rel","stylesheet");z.setAttribute("href",URI(s.staticMimeUrlPrefix+"zen_rt_framework/resources/css/zen.css").normalize().toString());document.getElementsByTagName("head")[0].appendChild(z);};
sap.zen.dsh.AnalyticGrid.prototype.onAfterRendering=function(){this.doInit();};
sap.zen.dsh.AnalyticGrid.prototype.logoff=function(){if(window[this.getId()+"Buddha"]){if(!this.loggedOff){this.loggedOff=true;window.buddhaHasSendLock++;window[this.getId()+"Buddha"].exec("APPLICATION.logoff();");}}};
sap.zen.dsh.AnalyticGrid.prototype.exit=function(){this.logoff();var r=sap.ui.getCore().byId(this.sId+"ROOT_absolutelayout");if(r){r.destroy();}if(sapbi_dshControl&&sapbi_dshControl===this){sapbi_dshControl=undefined;}};
sap.zen.dsh.AnalyticGrid.prototype.addParameter=function(n,v){this.parameters[n]=v;};
sap.zen.dsh.AnalyticGrid.prototype.executeScript=function(s){this.page.exec(s);};
sap.zen.dsh.AnalyticGrid.prototype.initializeSelectionVariant=function(s){function a(O,v,V){if(!v.hasOwnProperty(O)){v[O]=V;}}oNavParams={};if(s){var p=s.Parameters;var S=s.SelectOptions;if(p){for(var b=0;b<p.length;b++){var P=p[b];oNavParams[P.PropertyName]=P.PropertyValue;}}if(S){for(var i=0;i<S.length;++i){var o=S[i];var r=o.Ranges;var f=[];for(var j=0;j<r.length;++j){var R=r[j];if(R.Sign!=="I"){continue;}var c=R.Option||"EQ";if(c==="EQ"){filterValue=R.Low;}else{filterValue={};if(c==="BT"){filterValue.low=R.Low;filterValue.high=R.High;}else if(c==="LE"){filterValue.low=R.Low;}else if(c==="GE"){filterValue.high=R.Low;}}f.push(filterValue);}if(f.length>0){a(o.PropertyName,oNavParams,f);}}}}if(!jQuery.isEmptyObject(oNavParams)){this.addParameter("NAV_PARAMS",JSON.stringify(oNavParams));}}
