/* (c) Copyright 2012-2014 SAP AG. All rights reserved
 */
jQuery.sap.declare("sap.apf.ui.utils.printModel");jQuery.sap.require("sap.apf.ui.utils.formatter");jQuery.sap.require("sap.viz.ui5.types.legend.Common");
sap.apf.ui.utils.PrintModel=function(i){this.oUiApi=i.uiApi;this.oCoreApi=i.oCoreApi;this.oFilterIdHandler=i.oFilterIdHandler;};
sap.apf.ui.utils.PrintModel.prototype.constructor=sap.apf.ui.utils.PrintModel;
function _getAllTheConfiguredSmartFilters(p){var s=p.oUiApi.getSmartFilterForPrint();var f=[];if(s!==undefined&&s!==null){var S=s.getFilterData();var a;for(a in S){var t="";var l=S[a]['ranges'];for(var v=0;v<l.length;v++){if(v!==l.length-1){t+=l[v]['tokenText']+", ";}else{t+=l[v]['tokenText'];}}f.push({sFilterName:a,sFilterValue:t});}}return f;}
function _getAllTheConfiguredFacetFilters(p){var n,f="",F;var o,a,b=[],s=[],S=[];o=p.oUiApi.getFacetFilterForPrint();if(o){a=o.getLists();for(n=0;n<a.length;n++){f=a[n].getTitle();if(!a[n].getSelectedItems().length){S=a[n].getItems();}else{S=a[n].getSelectedItems();}s=_getTextsFromSelectedItems(S);if(f!==undefined&&f!==null){F="";for(var j=0;j<s.length;j++){if(j!==s.length-1){F+=s[j]+", ";}else{F+=s[j];}}b.push({sFilterName:f,sFilterValue:F});}}}return b;}
function _getTextsFromSelectedItems(s){var S=[];s.forEach(function(i){S.push(i.getText());});return S;}
function _getApplicationSpecificFiltersExpression(p){var a=p.oFilterIdHandler.getAllInternalIds();var A,b=[],i;if(a.length>0){for(i=0;i<a.length;i++){A=p.oFilterIdHandler.get(a[i]).getExpressions();b.push(A[0]);}}return b;}
function _getPrepareFormattedFilterValues(p,a){var A=[],i,j,f="",F,o,P;var b=[];function c(P){f="";b=[];f=P.label;var o=new sap.apf.ui.utils.formatter({getEventCallback:p.oUiApi.getEventCallback.bind(p.oUiApi),getTextNotHtmlEncoded:p.oCoreApi.getTextNotHtmlEncoded,getExits:p.oUiApi.getCustomFormatExit()},P);b.push(o.getFormattedValue(P.name,a[i][j].value));}for(i=0;i<a.length;i++){for(j=0;j<a[i].length;j++){p.oCoreApi.getMetadataFacade().getProperty(a[i][j].name).done(function(m){P=m;f="";b=[];f=m.label;o=new sap.apf.ui.utils.formatter({getEventCallback:p.oUiApi.getEventCallback.bind(p.oUiApi),getTextNotHtmlEncoded:p.oCoreApi.getTextNotHtmlEncoded,getExits:p.oUiApi.getCustomFormatExit()},m);});b.push(o.getFormattedValue(P.name,a[i][j].value));if(f!==undefined&&f!==null){F="";for(var j=0;j<b.length;j++){if(j!==b.length-1){F+=b[j]+", ";}else{F+=b[j];}}A.push({sFilterName:f,sFilterValue:F});}}}return A;}
function _getAllTheConfiguredAppSpecificFormattedFilters(p){var c=p.oUiApi.getEventCallback(sap.apf.core.constants.eventTypes.printTriggered);var a=_getPrepareFormattedFilterValues(p,_getApplicationSpecificFiltersExpression(p));if(c!==undefined){var b={getTextNotHtmlEncoded:p.oCoreApi.getTextNotHtmlEncoded};a=c.apply(b,_getApplicationSpecificFiltersExpression(p));}return a;}
function _getFormattedFilters(p){var f,a,F;var b=_getAllTheConfiguredFacetFilters(p);a=_getAllTheConfiguredSmartFilters(p);f=_getAllTheConfiguredAppSpecificFormattedFilters(p);F=f.concat(a,b);return F;}
sap.apf.ui.utils.PrintModel.prototype.getFiltersToPrint=function(){var p=this;var f=_getFormattedFilters(p);return f;};
sap.apf.ui.utils.PrintModel.prototype.getHeaderForFirstPage=function(){return this.oUiApi.getAnalysisPath().oSavedPathName.getTitle();};
sap.apf.ui.utils.PrintModel.prototype.getApplicationName=function(){var m;var a=this.applicationConfig.appName;if(!a){m=this.oCoreApi.createMessageObject({code:"6003",aParameters:["sAppName"]});this.oCoreApi.putMessage(m);}return a;};
sap.apf.ui.utils.PrintModel.prototype.setApplicationConfig=function(c){this.applicationConfig=c;};
sap.apf.ui.utils.PrintModel.prototype.getRepresentationForPrint=function(s){var p;var S=this.oCoreApi.getTextNotHtmlEncoded(s.title);var o=s.getSelectedRepresentation();var a=o.bIsAlternateView?o.toggleInstance:o;p=a.getPrintContent(S);return p.oRepresentation;};
